AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Shopify Webhooks

Globals:
  Function:
    Timeout: 30
    Runtime: nodejs18.x
    MemorySize: 128

Resources:
  checkoutQueue:
    Type: AWS::SQS::Queue
  orderQueue:
    Type: AWS::SQS::Queue
  updateQueue:
    Type: AWS::SQS::Queue

  HookApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: test


  ValidateHmac:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: getHmac/
      Handler: handler.handler
      Environment:
        Variables:
          webhook_verify_hash: 096df16dbcd3e39682f5b8a4dc5d048b84e7248e6488145c12544641ec049f3b
          CHECKOUT_QUEUE_ARN: !Ref checkoutQueue
          ORDER_QUEUE_ARN: !Ref orderQueue
          UPDATE_QUEUE_ARN: !Ref  updateQueue
      Policies: 
        - SQSSendMessagePolicy:
            QueueName: !GetAtt checkoutQueue.QueueName
        - SQSSendMessagePolicy:
            QueueName: !GetAtt orderQueue.QueueName
        - SQSSendMessagePolicy:
            QueueName: !GetAtt updateQueue.QueueName
      Events:
        CartUpdateHook:
          Type: Api
          Properties:
            Path: /cart/update
            Method: Post
            RestApiId: !Ref HookApi
        CartCheckoutHook:
          Type: Api
          Properties:
            Path: /cart/checkout
            Method: Post
            RestApiId: !Ref HookApi
        OrderHook:
          Type: Api
          Properties:
            Path: /order/complete
            Method: Post
            RestApiId: !Ref HookApi
  
  CheckoutFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: getCheckout/
      Handler: checkoutHandler.handler
      Events:
        SQSCheckoutEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt checkoutQueue.Arn 

  
  OrderFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: getOrder/
      Handler: orderHandler.handler
      Events:
        SQSCheckoutEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt orderQueue.Arn 
  

  UpdateFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: getUpdate/
      Handler: updateHandler.handler
      Events:
        SQSCheckoutEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt updateQueue.Arn 




  # BodyHookFunction:
  #   Type: AWS::Serverless::Function
  #   Properties:
  #     CodeUri: getBody/
  #     Handler: getBody.handler
            